### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by bkenn** [timrs2998/pdf-builder#14]
Are there any plans to allow images? I cannot seem to find a function to add images.

**Comment by timrs2998** [comment]
Sorry I haven't gotten back to you, I had notifications disabled for a while. Yes I think if I find some time to work on this project again, I'll be working on these issues I've laid out here. Otherwise feel free to submit a pull request or even fork the project for your uses. 

Duplicate of https://github.com/timrs2998/pdf-builder/issues/11

**Comment by timrs2998** [comment]
resolved by https://github.com/timrs2998/pdf-builder/pull/17
