### ISSUE TITLE
Missing gradle dependencies for pdfbox and kotlin stdlib in release 1.3.1 - 1.5.0

### ISSUE THREAD

**Issue by siduenho** [timrs2998/pdf-builder#19]
Hi Tim,

thanks for this library. I was about to use it in my project. I added your example code from the README and I got the following error on `document {`: 

> Cannot access class 'org.apache.pdfbox.pdmodel.PDDocument'. Check your module classpath for missing or conflicting dependencies

I then added `compile "org.apache.pdfbox:pdfbox:2.0.17"` to my build.gradle file and everything worked as expected.

I was wondering, why you didn't already include pdfbox as dependency for your library. You didn't mention to include it manually in your README either. After I looked at https://mvnrepository.com/artifact/com.github.timrs2998/pdf-builder?repo=jcenter I saw the problem.

When I click on version 1.3.0, I can see the following configuration for your lib, just like I would've expected it to be.

> Compile Dependencies (2)
> org.apache.pdfbox » pdfbox
> org.jetbrains.kotlin » kotlin-stdlib

Starting from version 1.3.1 to 1.5.0 (in jcenter) this is missing. They all say:

> Compile Dependencies (0)

Currently, I've added the pdfbox dependency manually. But I would really appreciate, if you would configure it to include the dependencies directly.

Best Regards,
Simon

**Comment by timrs2998** [comment]
Sorry, you are correct. The docs are missing the pdfbox dependency. 

The intention was to use the new api/implementation way of declaring dependencies instead of deprecated compile way, and that apache pdfbox be an "api" dependency. I forgot to update the docs with this change. Couple of notes:
* compile dependencies are deprecated https://stackoverflow.com/a/44419574/1509183
* If pdfbox were an implementation dependency, then users would be forced to add pdfbox as implementation/compile dependencies anyways, since pdfbox isn't necessairly on the user's classpath. This is because the public api for pdf-builder uses classes in apache pdfbox as pdf-builder is intentionally a leaky abstraction.
* As an api dependency, you can specify which version of apache pdfbox you want to use inside your application as long as it's api compatible with the one used in pdf-builder.

**Comment by timrs2998** [comment]
So I know you want the dependency added so that users don't need to add pdfbox, however, I think the right solution is to have pdfbox as an "api" dependency (rather than implementation or compile). That makes sense because pdfbox is required on the user's classpath and is used in return types and method parameters on the public api for pdf-builder. Then update the documentation with instructions to add pdfbox as an additional dependency. Let me know your thoughts on that.

**Comment by siduenho** [comment]
At first: Thanks alot for the hint with compile and implementation keyword, I didn't know that.

I'm not an expert on this topic. But as far as I've understood I would agree to your conclusion for the API dependency and the updated documentation.

It would be cool if you mention pdfbox as the underlying base in your project short description, too. I was wondering how you create the pdf because some tools even use third party software your need to install.

**Comment by timrs2998** [comment]
FYI I updated the README.md to be explicit about relying on pdfbox and that it's a required dependency.
